### ISSUE TITLE
book errata - ASCII Codes

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [Apress/beginning-cpp20#34]
Where can errata get submitted for the book?

page 21 - ASCII Codes

> lowercase letters have the sixth bit as 0, and uppercase letters have the sixth bit as 1

This should be
> lowercase letters have the sixth bit as 1, and uppercase letters have the sixth bit as 0

**Comment by Peter-VanWeert** [comment]
Thank you for the feedback. The official way to submit errata is through https://www.apress.com/gp/services/errata, but for me raising an issue here on github is fine as well. I will look into this one of these days / weeks, and include it in the C++23 edition (and update the errata.md file for the C++20).

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> Thank you for the feedback. The official way to submit errata is through https://www.apress.com/gp/services/errata, but for me raising an issue here on github is fine as well. I will look into this one of these days / weeks, and include it in the C++23 edition (and update the errata.md file for the C++20).

Will you work with Ivor Horton on the C++23 edition?

**Comment by Peter-VanWeert** [comment]
> Will you work with Ivor Horton on the C++23 edition?

I have started work on Beginning C++23, yes.

Without Ivor Horton, though: he's enjoying his well-earned retirement. In fact, it has just been me ever since Beginning C++17. I expect that his name will remain on the book for at least a few more editions, though, out of respect for his excellent work the first four editions, and also because of his reputation that still lives on.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> In fact, it has just been me ever since Beginning C++17. I expect that his name will remain on the book for at least a few more editions, though, out of respect for his excellent work the first four editions, and also because of his reputation that still lives on.

Wow, I didn't know that! Thanks for sharing the story behind. You are so nice! I ask that question it's because I'm a long time reader of his books and I really love his writing style. I guess he's almost 80 years old and I'm amazed that he can still keep up with the newest technology. Haha now I know he's no longer in the technical loop and is enjoying his retirement. Thanks again!
